export const problems = [
  {
    id: "m1",
    skill: "mix-k",
    level: "practice",
    prompt: "Let $k$, $2k$, and $k+60$ be consecutive terms of an arithmetic sequence. Find $k$.",
    answer: { type: "number", value: 30 },
    input: { kind: "text", placeholder: "k" },
    need: {
      goal: "$k$",
      have: "three terms in $k$, promised arithmetic",
      first: "Use $2\\times(\\text{middle})=\\text{first}+\\text{third}$.",
    },
    hints: [
      {
        k: "Why twice the middle",
        b: "If three terms are arithmetic, the two gaps are equal, so $2\\times(\\text{middle term})=\\text{first}+\\text{third}$. That is the test IB wants written down before any algebra.",
      },
      {
        k: "Solve, then check the list",
        b: "$2(2k)=k+(k+60) \\Rightarrow 4k=2k+60 \\Rightarrow k=30$. The terms are $30,\\ 60,\\ 90$, with $d=30$. If you got $k=60$ you used the wrong pairing.",
      },
    ],
    solution: "$k=30$. The terms are $30,60,90$ with $d=30$.",
  },
  {
    id: "m2",
    skill: "mix-k",
    level: "practice",
    prompt: "Let $k$, $2k$, and $k+60$ be consecutive terms of a geometric sequence, with $k\\ne 0$. Find $k$.",
    answer: { type: "number", value: 20 },
    input: { kind: "text", placeholder: "k" },
    need: {
      goal: "$k$",
      have: "three terms, promised geometric",
      first: "Use $(\\text{middle})^2=\\text{first}\\times\\text{third}$.",
    },
    hints: [
      {
        k: "Why the middle-square test",
        b: "If three terms are geometric, $\\dfrac{u_2}{u_1}=\\dfrac{u_3}{u_2}$, so $u_2^2=u_1 u_3$. (Do not use the arithmetic test $2u_2=u_1+u_3$ here — that finds a different $k$.)",
      },
      {
        k: "Solve",
        b: "$(2k)^2=k(k+60) \\Rightarrow 4k^2=k^2+60k$. Since $k\\neq 0$, divide by $k$: $4k=k+60$, so $k=20$. Terms $20,\\ 40,\\ 80$ with $r=2$.",
      },
    ],
    solution: "$k=20$. Terms $20,40,80$, ratio $2$.",
  },
  {
    id: "m3",
    skill: "mix-k",
    level: "challenge",
    prompt: "The first three terms of a sequence are $k-5$, $3-2k$, and $5k+3$. Given that the sequence is arithmetic, find $k$.",
    answer: { type: "number", value: 0.8 },
    input: { kind: "text", placeholder: "k" },
    need: {
      goal: "$k$",
      have: "three terms in $k$, and the sequence is arithmetic",
      first: "Set $2u_2=u_1+u_3$. This is linear, so there is one value of $k$. (The geometric case for the same three terms is a different, usually quadratic, equation.)",
    },
    hints: [
      { k: "Write the arithmetic condition", b: "Why this equation: equal steps mean $2(3-2k)=(k-5)+(5k+3)$." },
      { k: "Expand", b: "$6-4k=6k-2$." },
      { k: "Collect", b: "$8=10k$." },
    ],
    solution: "$k=4/5=0.8$.",
  },
  {
    id: "m4",
    skill: "mix-inside",
    level: "challenge",
    prompt: "The $3$rd, $4$th and $7$th terms of an arithmetic sequence (common difference $d\\ne 0$) are the first three terms of a geometric sequence. If $u_1=a$, show-style calculation gives $a=-\\frac{3}{2}d$. Find the common ratio of that geometric sequence.",
    answer: { type: "number", value: 3 },
    input: { kind: "text", placeholder: "r" },
    need: {
      goal: "the common ratio of the geometric sequence",
      have: "$a=-\\frac{3}{2}d$, and terms $u_3,u_4,u_7$",
      first: "Write $u_3,u_4,u_7$ in terms of $d$ only, then $r=u_4/u_3$.",
    },
    hints: [
      { k: "Write the three arithmetic terms", b: "$u_3=a+2d=-\\dfrac{3}{2}d+2d=\\dfrac{1}{2}d$, $u_4=a+3d=\\dfrac{3}{2}d$, $u_7=a+6d=\\dfrac{9}{2}d$." },
      { k: "Ratio", b: "$r=u_4/u_3=(\\frac{3}{2}d)/(\\frac{1}{2}d)=3$. Check: $u_7/u_4=(9/2)d/(3/2)d=3$." },
    ],
    solution: "$r=3$.",
  },
  {
    id: "m5",
    skill: "mix-inside",
    level: "challenge",
    prompt: "The first three terms of a geometric sequence are also the $1$st, $11$th and $16$th terms of an arithmetic sequence. All geometric terms are different, and $S_\\infty=18$ for the geometric sequence. Find the common ratio $r$ of the geometric sequence.",
    answer: { type: "number", value: 0.5 },
    input: { kind: "text", placeholder: "r" },
    need: {
      goal: "$r$",
      have: "geometric terms sitting at arithmetic positions $1$, $11$ and $16$, and $S_{\\infty}=18$",
      first: "The arithmetic gaps are $10$ steps then $5$ steps, so the second jump is half the first. For a geometric sequence that forces $r=\\dfrac{1}{2}$ (and $r\\neq 1$).",
    },
    hints: [
      { k: "Write the three arithmetic terms as a geometric sequence", b: "Let them be $a$, $a+10d$, $a+15d$. Then $(a+10d)^2=a(a+15d)$." },
      { k: "Simplify", b: "$20ad+100d^2=15ad \\Rightarrow 5d(a+20d)=0$, so $a=-20d$." },
      { k: "Read $r$", b: "$r=(a+10d)/a=(-10d)/(-20d)=1/2$. (Reject $r=1$ because the terms must be different.)" },
    ],
    solution: "$r=1/2$. Then $S_\\infty=u/(1-r)=18$ gives first geometric term $9$.",
  },
  {
    id: "m6",
    skill: "mix-max",
    level: "challenge",
    prompt: "An arithmetic sequence has $u_1=80$ and $d=-6.32$. Find the greatest value of $S_n$, to two decimal places.",
    answer: { type: "number", value: 547.04, tol: 0.02 },
    input: { kind: "text", placeholder: "greatest Sn" },
    need: {
      goal: "the maximum partial sum",
      have: "a decreasing arithmetic sequence ($d<0$)",
      first: "Sums increase while $u_n>0$ and start falling once terms become negative. Find the last positive term, then compare $S_n$ and $S_{n+1}$ around that index.",
    },
    hints: [
      { k: "When do terms change sign?", b: "$80+(n-1)(-6.32)=0 \\Rightarrow n-1=80/6.32\\approx 12.66$, so $u_{13}>0$ and $u_{14}<0$." },
      { k: "Compute both nearby sums", b: "$S_{13}=\\frac{13}{2}\\bigl(160+12(-6.32)\\bigr)=\\frac{13}{2}(160-75.84)$." },
      { k: "Evaluate", b: "$\\frac{13}{2}\\times 84.16=13\\times 42.08=547.04$. Then $S_{14}=547.04+u_{14}$ is smaller because $u_{14}<0$." },
    ],
    solution: "$547.04$.",
  },
  {
    id: "m7",
    skill: "mix-compare",
    level: "practice",
    prompt: "John swims lengths in an arithmetic sequence of times: first length $2$ minutes, each next length $0.1$ minutes more. Find the time for his $10$th length.",
    answer: { type: "number", value: 2.9 },
    input: { kind: "text", placeholder: "minutes" },
    need: {
      goal: "$u_{10}$ of an AP",
      have: "$u_1=2$, $d=0.1$",
      first: "This is an $n^{\\text{th}}$-term question, not a sum.",
    },
    hints: [
      { k: "Formula", b: "$u_{10}=2+9\\times 0.1$." },
    ],
    solution: "$2.9$ minutes.",
  },
  {
    id: "m8",
    skill: "mix-compare",
    level: "practice",
    prompt: "Ann swims lengths in a geometric sequence of times: first length $2$ minutes, common ratio $1.05$. Find the total time for $10$ lengths, to $3$ decimal places.",
    answer: { type: "number", value: 25.156, tol: 0.002 },
    input: { kind: "text", placeholder: "total minutes" },
    need: {
      goal: "$S_{10}$ of a GP",
      have: "$u_1=2$, $r=1.05$, $n=10$",
      first: "This is a total, so use the finite geometric sum.",
    },
    hints: [
      { k: "Formula", b: "$S_{10}=2(1.05^{10}-1)/(1.05-1)=40(1.05^{10}-1)$." },
      { k: "Evaluate", b: "$1.05^{10}\\approx 1.62889462677$, so $40\\times 0.62889462677$." },
    ],
    solution: "$25.156$ minutes.",
  },
];
