export const problems = [
  {
    id: "gs1",
    skill: "gsum-finite",
    level: "foundation",
    prompt: "A geometric sequence has $u_1=10$ and $r=2$. Find $S_{10}$, the sum of the first $10$ terms.",
    answer: { type: "number", value: 10230 },
    input: { kind: "text", placeholder: "S10" },
    need: {
      goal: "$S_{10}$",
      have: "$u_1=10$, $r=2$, $n=10$",
      first: "The booklet form is $S_n=\\dfrac{u_1(r^n-1)}{r-1}$. You already have $u_1$, $r$ and $n$.",
    },
    hints: [
      {
        k: "Why this is a sum, not a term",
        b: "$u_{10}$ would be $10\\times 2^{9}$. $S_{10}$ adds the first ten terms. Different questions, different formulae.",
      },
      {
        k: "Substitute",
        b: "$S_{10}=\\dfrac{10(2^{10}-1)}{2-1}=10(1024-1)=10230$.",
      },
    ],
    solution: "$10230$.",
  },
  {
    id: "gs2",
    skill: "gsum-finite",
    level: "practice",
    prompt: "A geometric sequence has $u_1=8$ and $r=\\dfrac{1}{2}$. Find $S_{12}$.",
    answer: { type: "number", value: 15.984375 },
    input: { kind: "text", placeholder: "S12" },
    need: {
      goal: "$S_{12}$",
      have: "$u_1=8$, $r=1/2$, $n=12$",
      first: "Because $\\left|\\dfrac{1}{2}\\right|<1$, the booklet form $S_n=\\dfrac{u_1(1-r^n)}{1-r}$ is the comfortable one. Paper 1: leave the answer as a fraction if you can.",
    },
    hints: [
      {
        k: "Why the $(1-r^n)$ form",
        b: "When $|r|<1$, writing $1-r^n$ on top keeps the numbers small and positive. The two booklet forms are algebraically the same.",
      },
      {
        k: "Compute exactly",
        b: "$S_{12}=8\\dfrac{1-\\left(\\dfrac{1}{2}\\right)^{12}}{1-\\dfrac{1}{2}}=16\\left(1-\\dfrac{1}{4096}\\right)=\\dfrac{65520}{4096}=15.984375$.",
      },
    ],
    solution: "$15.984375$ (or $65520/4096$).",
  },
  {
    id: "gs3",
    skill: "gsum-finite",
    level: "practice",
    prompt: "Fees of $2000$, $2500$, $3125$ continue geometrically. Find the total for the first six years, to the nearest dollar.",
    answer: { type: "number", value: 22518 },
    input: { kind: "text", placeholder: "total, nearest dollar" },
    need: {
      goal: "$S_6$ rounded",
      have: "$u_1=2000$, $r=1.25$",
      first: "Find $r$ from the first two fees, then use the finite geometric sum with $n=6$.",
    },
    hints: [
      { k: "Common ratio", b: "$r=2500/2000=1.25$." },
      { k: "Sum", b: "$S_6=2000(1.25^6-1)/(1.25-1)=8000(1.25^6-1)$." },
      { k: "Evaluate", b: "$1.25^6=3.814697265625$, so $S_6=8000\\times 2.814697265625=22517.578\\ldots$" },
    ],
    solution: "$22518$ (nearest dollar).",
  },
  {
    id: "gs4",
    skill: "gsum-inf",
    level: "foundation",
    prompt: "The first three terms of an infinite geometric sequence are $32,\\ 16,\\ 8$. Find $S_{\\infty}$.",
    answer: { type: "number", value: 64 },
    input: { kind: "text", placeholder: "S∞" },
    need: {
      goal: "$S_{\\infty}$",
      have: "$u_1=32$ and $r$ from the list",
      first: "Find $r$ from the first two terms, check $|r|<1$ (otherwise you must not use $S_{\\infty}$), then $S_{\\infty}=\\dfrac{u_1}{1-r}$.",
    },
    hints: [
      {
        k: "Why we check $|r|$ before summing forever",
        b: "The formula $S_{\\infty}=\\dfrac{u_1}{1-r}$ is in the booklet with the condition $|r|<1$. If you skip that check you can “find” a sum that does not exist — and lose the explain mark on AHL papers.",
      },
      {
        k: "Then the formula",
        b: "$r=\\dfrac{16}{32}=\\dfrac{1}{2}$, and $\\left|\\dfrac{1}{2}\\right|<1$, so $S_{\\infty}=\\dfrac{32}{1-\\dfrac{1}{2}}=\\dfrac{32}{\\dfrac{1}{2}}=64$.",
      },
    ],
    solution: "$64$.",
  },
  {
    id: "gs5",
    skill: "gsum-inf",
    level: "practice",
    prompt: "Find the sum of the infinite geometric sequence $27, -9, 3, -1, \\ldots$.",
    answer: { type: "number", value: 20.25 },
    input: { kind: "text", placeholder: "S∞" },
    need: {
      goal: "$S_\\infty$",
      have: "an alternating geometric list",
      first: "Find $r$ (it is negative). Check $|r|<1$ before summing.",
    },
    hints: [
      { k: "Ratio", b: "$r=-9/27=-1/3$, and $|r|=1/3<1$." },
      { k: "Formula", b: "$S_\\infty=27/(1-(-1/3))=27/(4/3)=27\\times 3/4$." },
    ],
    solution: "$81/4=20.25$.",
  },
  {
    id: "gs6",
    skill: "gsum-inf",
    level: "practice",
    prompt: "Consider $10, 20, 40, 80, \\ldots$. Why does $S_\\infty$ not exist? Choose the best reason.",
    answer: { type: "choice", correct: "r-big" },
    input: {
      kind: "choice",
      options: [
        { id: "r-big", label: "$|r|=2>1$, so the terms grow and do not tend to zero." },
        { id: "neg", label: "The terms are positive, and infinite sums of positive terms never exist." },
        { id: "n", label: "We were not told the value of $n$." },
      ],
    },
    need: {
      goal: "a reason the infinite sum diverges",
      have: "$r=2$",
      first: "The test is $|r|<1$. Here it fails.",
    },
    hints: [
      { k: "The only test that matters", b: "$S_\\infty$ exists only when $|r|<1$. Here $r=2$." },
    ],
    solution: "$|r|=2>1$, so the terms do not tend to zero.",
  },
  {
    id: "gs7",
    skill: "gsum-inf",
    level: "challenge",
    prompt: "The first term of an infinite geometric sequence is $18$ and the third term is $8$. Using the positive common ratio, find $S_\\infty$.",
    answer: { type: "number", value: 54 },
    input: { kind: "text", placeholder: "S∞" },
    need: {
      goal: "$S_\\infty$ for $r>0$",
      have: "$u_1=18$, $u_3=8$",
      first: "Find $r$ from $18 r^2=8$. Keep the positive root, then use $u_1/(1-r)$.",
    },
    hints: [
      { k: "Find $r$ first", b: "$r^2=8/18=4/9$, so $r=2/3$ (positive case)." },
      { k: "Check convergence", b: "$|2/3|<1$, so $S_\\infty=18/(1-2/3)=18/(1/3)$." },
    ],
    solution: "$54$.",
  },
  {
    id: "gs8",
    skill: "gsum-n",
    level: "practice",
    prompt: "A geometric sequence has $u_1=1/81$ and $r=3$. Find the smallest $n$ such that $S_n>40$.",
    answer: { type: "number", value: 8 },
    input: { kind: "text", placeholder: "n" },
    need: {
      goal: "smallest $n$ with $S_n>40$",
      have: "$u_1=1/81$, $r=3$",
      first: "Write $S_n=u_1(r^n-1)/(r-1)$ and solve the inequality. Then check $S_{n-1}$ and $S_n$.",
    },
    hints: [
      { k: "Sum formula", b: "$S_n=\\frac{1}{81}\\cdot\\frac{3^n-1}{2}=\\frac{3^n-1}{162}$." },
      { k: "Inequality", b: "$3^n-1>6480$, so $3^n>6481$. Now $3^8=6561$ and $3^7=2187$." },
      { k: "Confirm", b: "$S_7=(2187-1)/162=13.49<40$ and $S_8=(6561-1)/162=40.49>40$." },
    ],
    solution: "$n=8$.",
  },
  {
    id: "gs9",
    skill: "gsum-n",
    level: "challenge",
    prompt: "A geometric sequence has $u_1=1024$ and $r=1/2$. Find the smallest $n$ such that $S_n>2047.968$.",
    answer: { type: "number", value: 16 },
    input: { kind: "text", placeholder: "n" },
    need: {
      goal: "first $n$ with $S_n$ past $2047.968$",
      have: "$u_1=1024$, $r=1/2$",
      first: "Note $S_\\infty=2048$. You are a tiny step below infinity, so $n$ will be large. Use $S_n=2048(1-2^{-n})$.",
    },
    hints: [
      { k: "Closed form", b: "$S_n=1024\\frac{1-(1/2)^n}{1/2}=2048\\bigl(1-2^{-n}\\bigr)$." },
      { k: "Inequality", b: "$2048(1-2^{-n})>2047.968 \\Rightarrow 1-2^{-n}>0.999984375 \\Rightarrow 2^{-n}<0.000015625=2^{-16}$." },
      { k: "Read the power", b: "So $n\\ge 16$. Check $S_{15}=2048(1-2^{-15})=2047.9375<2047.968$." },
    ],
    solution: "$n=16$.",
  },
  {
    id: "gs10",
    skill: "gsum-decimal",
    level: "challenge",
    prompt: "The infinite series $\\sum_{k=0}^{\\infty} \\dfrac{47}{1000}\\left(\\dfrac{1}{100}\\right)^k$ equals $S_\\infty$. Find $S_\\infty$ as a fraction in lowest terms. Enter numerator then denominator.",
    answer: { type: "list", values: [47, 990] },
    input: { kind: "text", placeholder: "numerator, denominator" },
    need: {
      goal: "$S_\\infty$ as a reduced fraction",
      have: "first term $47/1000$ and ratio $1/100$",
      first: "Check $|r|<1$, then $S_\\infty=u_1/(1-r)$. Simplify the fraction.",
    },
    hints: [
      { k: "Identify $u_1$ and $r$", b: "$u_1=47/1000$, $r=1/100$." },
      { k: "Formula", b: "$S_\\infty=\\dfrac{47/1000}{1-1/100}=\\dfrac{47/1000}{99/100}=\\dfrac{47}{1000}\\cdot\\dfrac{100}{99}$." },
      { k: "Simplify", b: "$\\dfrac{47}{10\\times 99}=\\dfrac{47}{990}$." },
    ],
    solution: "$47/990$.",
  },
  {
    id: "gs11",
    skill: "gsum-x",
    level: "challenge",
    prompt: "The series $\\sum_{k=1}^{\\infty} 2(4x-3)^{k-1}$ converges for certain $x$. Find the largest possible $x$ for which it converges. (Open interval; give the open upper bound.)",
    answer: { type: "number", value: 1 },
    input: { kind: "text", placeholder: "upper bound for x" },
    need: {
      goal: "the upper end of the interval of $x$",
      have: "a geometric series with ratio $4x-3$",
      first: "Convergence needs $|r|<1$, i.e. $|4x-3|<1$.",
    },
    hints: [
      { k: "Common ratio", b: "$r=4x-3$ (first term $2$ when $k=1$)." },
      { k: "Inequality", b: "$-1<4x-3<1 \\Rightarrow 2<4x<4 \\Rightarrow 1/2<x<1$." },
      { k: "Largest possible $x$ in the open interval", b: "The series converges for $x<1$, so the upper bound is $1$ (not included)." },
    ],
    solution: "The interval is $1/2<x<1$. The upper bound is $1$.",
  },
  {
    id: "gs12",
    skill: "gsum-x",
    level: "challenge",
    prompt: "For the geometric series $\\sum_{k=1}^{\\infty} 2(4x-3)^{k-1}$ with $x=0.7$, find $S_\\infty$. Give an exact fraction: numerator then denominator.",
    answer: { type: "list", values: [5, 3] },
    input: { kind: "text", placeholder: "numerator, denominator" },
    need: {
      goal: "$S_\\infty$ at $x=0.7$",
      have: "$u_1=2$ and $r=4x-3$",
      first: "Compute $r$, check $|r|<1$, then $2/(1-r)$.",
    },
    hints: [
      { k: "Find $r$", b: "$r=4(0.7)-3=2.8-3=-0.2$." },
      { k: "Sum", b: "$S_\\infty=2/(1-(-0.2))=2/1.2=20/12=5/3$." },
    ],
    solution: "$5/3$.",
  },
];
