export const problems = [
  {
    id: "r1",
    skill: "rec-arithgeo",
    level: "foundation",
    prompt: "A sequence is given by $u_1=10$ and $u_{n+1}=u_n+10$. Find $S_3$.",
    answer: { type: "number", value: 60 },
    input: { kind: "text", placeholder: "S3" },
    need: {
      goal: "$S_3$",
      have: "a recursive arithmetic rule",
      first: "Generate $u_1,u_2,u_3$ in order, then add. Do not skip to a sum formula until you know the terms.",
    },
    hints: [
      { k: "Terms first", b: "$10$, then $20$, then $30$." },
      { k: "Add", b: "$S_3=10+20+30$." },
    ],
    solution: "$60$.",
  },
  {
    id: "r2",
    skill: "rec-arithgeo",
    level: "practice",
    prompt: "A sequence is given by $u_1=7$ and $u_{n+1}=r\\,u_n$. The third term is $28$ and every term is positive. Find $r$.",
    answer: { type: "number", value: 2 },
    input: { kind: "text", placeholder: "r" },
    need: {
      goal: "$r$",
      have: "a recursive geometric rule, $u_1$, $u_3$, and positivity",
      first: "The rule $u_{n+1}=r\\,u_n$ is the recursive form of a geometric sequence, so $u_3=u_1 r^{2}$. Take the positive square root because every term is positive.",
    },
    hints: [
      { k: "Why this is geometric", b: "Each term is the previous one multiplied by the same $r$. That is the definition of a geometric sequence, written as a recipe. You already have $u_n=u_1 r^{n-1}$ from unit 04." },
      { k: "Equation", b: "$7r^2=28$, so $r^2=4$." },
      { k: "Sign", b: "Positive terms force $r=2$, not $r=-2$." },
    ],
    solution: "$r=2$.",
  },
  {
    id: "r3",
    skill: "rec-mixed",
    level: "practice",
    prompt: "A sequence is defined by $u_1=1$ and $u_{n+1}=2u_n+10$. Find $u_3$.",
    answer: { type: "number", value: 34 },
    input: { kind: "text", placeholder: "u3" },
    need: {
      goal: "$u_3$",
      have: "$u_1$ and a mixed recursive rule",
      first: "This is not a purely arithmetic or geometric rule. Compute $u_2$ from $u_1$, then $u_3$ from $u_2$.",
    },
    hints: [
      { k: "Second term", b: "$u_2=2(1)+10=12$." },
      { k: "Third term", b: "$u_3=2(12)+10$." },
    ],
    solution: "$34$.",
  },
  {
    id: "r4",
    skill: "rec-mixed",
    level: "challenge",
    prompt: "A sequence is defined by $u_1=4$ and $u_{n+1}=3u_n-2$. Find $u_3$.",
    answer: { type: "number", value: 28 },
    input: { kind: "text", placeholder: "u3" },
    need: {
      goal: "$u_3$",
      have: "$u_1$ and a mixed recursive rule",
      first: "This is not purely arithmetic (we do not add a constant) and not purely geometric (we do not only multiply). Compute $u_2$ from $u_1$, then $u_3$ from $u_2$.",
    },
    hints: [
      { k: "Why we cannot skip", b: "A recursive rule only gives the next term from the one you already have. There is no $u_n$ formula here yet, so $u_3$ has to go through $u_2$." },
      { k: "Second term", b: "$u_2=3(4)-2=10$." },
      { k: "Third term", b: "$u_3=3(10)-2=28$." },
    ],
    solution: "$28$.",
  },
  {
    id: "r5",
    skill: "spec-tri",
    level: "practice",
    prompt: "Cans are stacked in a triangle: $n$ on the bottom row, then $n-1$, down to $1$. A pile has $20$ cans in the bottom row. How many cans are in the pile?",
    answer: { type: "number", value: 210 },
    input: { kind: "text", placeholder: "total cans" },
    need: {
      goal: "$1+2+\\cdots+20$",
      have: "an arithmetic sequence of row sizes",
      first: "This is the triangular number $S_{20}=n(n+1)/2$ with $n=20$.",
    },
    hints: [
      { k: "Recognise the sum", b: "Bottom row $20$, next $19$, …, top $1$." },
      { k: "Formula", b: "$S=\\frac{20}{2}(1+20)=10\\times 21$." },
    ],
    solution: "$210$.",
  },
  {
    id: "r6",
    skill: "spec-tri",
    level: "challenge",
    prompt: "A triangular pile contains $3240$ cans. How many cans are in the bottom row?",
    answer: { type: "number", value: 80 },
    input: { kind: "text", placeholder: "bottom row" },
    need: {
      goal: "$n$ in $n(n+1)/2=3240$",
      have: "a triangular total",
      first: "Solve the quadratic $n^2+n-6480=0$. Keep the positive integer root.",
    },
    hints: [
      { k: "Equation", b: "$n(n+1)/2=3240 \\Rightarrow n^2+n-6480=0$." },
      { k: "Discriminant", b: "$1+25920=25921=161^2$." },
      { k: "Root", b: "$n=\\frac{-1+161}{2}=80$." },
    ],
    solution: "$80$.",
  },
  {
    id: "r7",
    skill: "spec-group",
    level: "challenge",
    prompt: "Positive integers are grouped $[1]$, then $[2,3,4,5]$, then $[6,7,8,9,10,11,12]$, and so on. Each group contains $3$ more integers than the previous group. How many integers are in the $20$th group?",
    answer: { type: "number", value: 58 },
    input: { kind: "text", placeholder: "size of group 20" },
    need: {
      goal: "the number of elements in group $20$",
      have: "group sizes $1,4,7,10,\\ldots$",
      first: "The sizes themselves form an arithmetic sequence with $u_1=1$ and $d=3$. Find $u_{20}$.",
    },
    hints: [
      { k: "Identify the arithmetic sequence of group sizes", b: "Group $n$ has $u_n=1+(n-1)3=3n-2$ integers. We use this because the group sizes themselves form an arithmetic sequence with $u_1=1$ and $d=3$." },
      { k: "Substitute", b: "$u_{20}=3(20)-2$." },
    ],
    solution: "$58$.",
  },
];
