/** Formal worked solutions for every practice item. Shown after a correct answer or if the student gives up. */
export const worked = {
  s1: [
    { t: "What the question wants", b: "Two numbers from a list: the first term $u_1$ and the fourth term $u_4$. The command term is <em>write down</em>, so we only read the list. There is no pattern to find." },
    { t: "How to read $u_n$", b: "The subscript is a position. $u_1$ is the 1st number written, $u_4$ is the 4th number written." },
    { t: "Working", b: "The list is $4,\\ 9,\\ 15,\\ 8,\\ 6,\\ \\ldots$ So position 1 is $4$, position 2 is $9$, position 3 is $15$, position 4 is $8$." },
    { t: "Answer", b: "$u_1=4$, $u_4=8$." },
  ],
  s2: [
    { t: "What the question wants", b: "$S_1$ and $S_3$. The letter $S$ means a running total, not a single term." },
    { t: "Meaning of $S_n$", b: "$S_n$ means add the first $n$ terms: $S_n=u_1+u_2+\\cdots+u_n$. In particular $S_1$ is just $u_1$." },
    { t: "Working", b: "The sequence is $3,\\ 8,\\ 13,\\ 18$. So $S_1=3$. Then $S_3=3+8+13=24$. (The $18$ is $u_4$, so it is not included in $S_3$.)" },
    { t: "Answer", b: "$S_1=3$, $S_3=24$." },
  ],
  s3: [
    { t: "What the question wants", b: "One term, $u_4$. We are given two totals, not the list." },
    { t: "The idea", b: "$S_4$ is everything up to term 4. $S_3$ is everything up to term 3. The extra piece is $u_4$. So $$u_4=S_4-S_3$$ We do not need the sequence to be arithmetic." },
    { t: "Working", b: "$u_4=40-31=9$." },
    { t: "Answer", b: "$u_4=9$." },
  ],
  s4: [
    { t: "What the question wants", b: "The first three terms of $u_n=10n$." },
    { t: "The idea", b: "An explicit formula means: put the position $n$ into the formula. For $u_1$ put $n=1$, and so on." },
    { t: "Working", b: "$u_1=10\\times 1=10$, $u_2=10\\times 2=20$, $u_3=10\\times 3=30$." },
    { t: "Answer", b: "$10,\\ 20,\\ 30$." },
  ],
  s5: [
    { t: "What the question wants", b: "$u_3$ from $u_n=10^n$." },
    { t: "Careful with notation", b: "$10^n$ is a power: $10$ multiplied by itself $n$ times. It is not $10n$ (ten times $n$)." },
    { t: "Working", b: "$u_3=10^3=10\\times 10\\times 10=1000$." },
    { t: "Answer", b: "$u_3=1000$." },
  ],
  s6: [
    { t: "What the question wants", b: "The first three terms of a recursive sequence." },
    { t: "The idea", b: "A recursive rule only tells you the next term from the one you already have. Start at the given $u_1$, then apply $u_{n+1}=u_n+10$ once, then once more." },
    { t: "Working", b: "$u_1=10$ is given. $u_2=10+10=20$. $u_3=20+10=30$." },
    { t: "Answer", b: "$10,\\ 20,\\ 30$." },
  ],
  s7: [
    { t: "What the question wants", b: "$u_3$, using $u_1=10$ and $u_{n+1}=2u_n+10$." },
    { t: "The idea", b: "You cannot jump two steps. First get $u_2$ from $u_1$. Then get $u_3$ from $u_2$. This rule is not “just add $10$” and not “just multiply by $2$”." },
    { t: "Working", b: "$u_2=2(10)+10=30$. Then $u_3=2(30)+10=70$." },
    { t: "Answer", b: "$u_3=70$." },
  ],
  s8: [
    { t: "What the question wants", b: "The value of $\\displaystyle\\sum_{r=1}^{3}(2r)$." },
    { t: "The idea", b: "Sigma means add. The index $r$ starts at $1$ and stops at $3$. Write the three terms, then add. Three terms do not need a series formula." },
    { t: "Working", b: "$2(1)+2(2)+2(3)=2+4+6=12$." },
    { t: "Answer", b: "$12$." },
  ],
  s9: [
    { t: "What the question wants", b: "$B-A$, where $A$ adds the first three terms of $2r+1$ and $B$ adds the first six." },
    { t: "The idea", b: "The sum from 1 to 6 is the sum from 1 to 3 plus the sum from 4 to 6. So $B-A=\\displaystyle\\sum_{r=4}^{6}(2r+1)$. Expand those three terms. Do not use an arithmetic-sum formula — that comes later." },
    { t: "Working", b: "$r=4$ gives $9$, $r=5$ gives $11$, $r=6$ gives $13$. Then $9+11+13=33$." },
    { t: "Answer", b: "$33$." },
  ],
  s10: [
    { t: "What the question wants", b: "The sum of the first three terms of $u_n=3\\times 2^{n}$." },
    { t: "The idea", b: "Substitute $n=1,2,3$ to write the three terms, then add. Three terms do not need a series formula." },
    { t: "Working", b: "$u_1=6$, $u_2=12$, $u_3=24$. Sum $6+12+24=42$." },
    { t: "Answer", b: "$42$." },
  ],
  a1: [
    { t: "What the question wants", b: "The common difference $d$ of an arithmetic sequence. “Write down” means read it off the list." },
    { t: "The idea", b: "Arithmetic means we <em>add the same number</em> each time. That number is $d=u_2-u_1$." },
    { t: "Working", b: "$d=15-11=4$. The next gap is $19-15=4$, so it really is common." },
    { t: "Answer", b: "$d=4$." },
  ],
  a2: [
    { t: "What the question wants", b: "The next term after $7,\\ 9.5,\\ 12$." },
    { t: "The idea", b: "First find the common difference, then add it once more. Without $d$ we cannot continue the list." },
    { t: "Working", b: "$d=9.5-7=2.5$. The last given term is $12$, so $u_4=12+2.5=14.5$." },
    { t: "Answer", b: "$u_4=14.5$." },
  ],
  a3: [
    { t: "What the question wants", b: "The value of $a$ that makes $a+3$, $2a+4$, $a+9$ arithmetic." },
    { t: "The idea", b: "Equal steps means twice the middle equals the two sides: $2u_2=u_1+u_3$." },
    { t: "Working", b: "$2(2a+4)=(a+3)+(a+9) \\Rightarrow 4a+8=2a+12 \\Rightarrow 2a=4 \\Rightarrow a=2$. The terms become $5,\\ 8,\\ 11$, which go up by $3$." },
    { t: "Answer", b: "$a=2$." },
  ],
  a4: [
    { t: "What the question wants", b: "$u_{11}$, given $u_1=-5$ and $d=8$." },
    { t: "The idea", b: "The formula booklet says $u_n=u_1+(n-1)d$. From term 1 to term 11 there are $10$ steps, not $11$." },
    { t: "Working", b: "$u_{11}=-5+(11-1)\\times 8=-5+80=75$." },
    { t: "Answer", b: "$u_{11}=75$." },
  ],
  a5: [
    { t: "What the question wants", b: "$u_{20}$ from the explicit formula $u_n=4n-1$." },
    { t: "The idea", b: "The $n^{\\text{th}}$ term is already written for us. Put $n=20$ in. We do not need to find $d$ separately." },
    { t: "Working", b: "$u_{20}=4(20)-1=80-1=79$." },
    { t: "Answer", b: "$u_{20}=79$." },
  ],
  a6: [
    { t: "What the question wants", b: "The $41^{\\text{st}}$ term of $7,\\ 9.5,\\ 12,\\ \\ldots$" },
    { t: "The idea", b: "The formula $u_n=u_1+(n-1)d$ needs $d$. We have $u_1=7$ and $n=41$, so find $d$ first." },
    { t: "Working", b: "$d=9.5-7=2.5$. Then $u_{41}=7+40\\times 2.5=7+100=107$." },
    { t: "Answer", b: "$u_{41}=107$." },
  ],
  a7: [
    { t: "What the question wants", b: "The common difference $d$, given $u_5=30$ and $u_{13}=70$." },
    { t: "The idea", b: "From position 5 to position 13 there are $13-5=8$ equal steps. So $u_{13}-u_5=8d$." },
    { t: "Working", b: "$d=\\dfrac{70-30}{8}=\\dfrac{40}{8}=5$." },
    { t: "Answer", b: "$d=5$." },
  ],
  a8: [
    { t: "What the question wants", b: "The first term $u_1$, given $u_5=30$ and $u_{13}=70$." },
    { t: "The idea", b: "We still need $d$ before we can walk back to $u_1$." },
    { t: "Working", b: "$d=\\dfrac{70-30}{8}=5$. Then $u_5=u_1+4d \\Rightarrow 30=u_1+20 \\Rightarrow u_1=10$. Check: $u_{13}=10+12\\times 5=70$." },
    { t: "Answer", b: "$u_1=10$." },
  ],
  a9: [
    { t: "What the question wants", b: "$u_1$, given $u_{21}=-37$ and $u_4=-3$." },
    { t: "The idea", b: "Match later minus earlier: $d=\\dfrac{u_{21}-u_4}{21-4}$. Keep both minus signs." },
    { t: "Working", b: "$d=\\dfrac{-37-(-3)}{17}=\\dfrac{-34}{17}=-2$. Then $u_4=u_1+3d \\Rightarrow -3=u_1+3(-2)=u_1-6 \\Rightarrow u_1=3$." },
    { t: "Answer", b: "$u_1=3$." },
  ],
  a10: [
    { t: "What the question wants", b: "The position $n$ for which the term equals $152$. This is $u_n$, not a sum." },
    { t: "The idea", b: "Set $u_1+(n-1)d=152$ and solve for $n$." },
    { t: "Working", b: "$2+3(n-1)=152 \\Rightarrow 3(n-1)=150 \\Rightarrow n-1=50 \\Rightarrow n=51$." },
    { t: "Answer", b: "$n=51$." },
  ],
  a11: [
    { t: "What the question wants", b: "How many terms of $11,\\ 15,\\ 19,\\ \\ldots$ are strictly less than $100$." },
    { t: "The idea", b: "Solve the inequality $u_n<100$, then check the neighbouring terms so rounding does not trick us." },
    { t: "Working", b: "$11+4(n-1)<100 \\Rightarrow 4(n-1)<89 \\Rightarrow n-1<22.25 \\Rightarrow n\\le 23$. Check: $u_{23}=99<100$ and $u_{24}=103>100$." },
    { t: "Answer", b: "$23$ terms." },
  ],
  a12: [
    { t: "What the question wants", b: "How many terms are in $3,\\ 9,\\ 15,\\ \\ldots,\\ 1353$, including both ends." },
    { t: "The idea", b: "Find $d$, then set $u_n=1353$. The last number on the page is $u_n$, not $S_n$." },
    { t: "Working", b: "$d=9-3=6$. Then $3+6(n-1)=1353 \\Rightarrow 6(n-1)=1350 \\Rightarrow n-1=225 \\Rightarrow n=226$." },
    { t: "Answer", b: "$n=226$." },
  ],
  a13: [
    { t: "What the question wants", b: "Seats in the $20^{\\text{th}}$ row, not the total in the theatre." },
    { t: "The idea", b: "Row number is $n$. Seats in that row is $u_n$. Use $u_n=u_1+(n-1)d$." },
    { t: "Working", b: "$u_{20}=15+19\\times 2=15+38=53$." },
    { t: "Answer", b: "$53$ seats." },
  ],
  a14: [
    { t: "What the question wants", b: "The day number on which she runs $10\\,\\text{km}$." },
    { t: "The idea", b: "Units must match. Convert kilometres to metres, then solve $u_n=10000$. This is a term, not a total distance." },
    { t: "Working", b: "$10\\,\\text{km}=10000\\,\\text{m}$. Then $1000+250(n-1)=10000 \\Rightarrow 250(n-1)=9000 \\Rightarrow n-1=36 \\Rightarrow n=37$." },
    { t: "Answer", b: "Day $37$." },
  ],
  a15: [
    { t: "What the question wants", b: "The common difference $d$ of the row sizes." },
    { t: "The idea", b: "From row 4 to row 8 there are $4$ steps, so $d=\\dfrac{u_8-u_4}{4}$." },
    { t: "Working", b: "$d=\\dfrac{32-20}{4}=3$." },
    { t: "Answer", b: "$d=3$." },
  ],
  as1: [
    { t: "What the question wants", b: "The sum of five arithmetic terms, first $2$ and last $32$." },
    { t: "The idea", b: "We have first, last, and $n$. Use the booklet form $S_n=\\dfrac{n}{2}(u_1+u_n)$. We do not need $d$." },
    { t: "Working", b: "$S_5=\\dfrac{5}{2}(2+32)=\\dfrac{5}{2}\\times 34=85$." },
    { t: "Answer", b: "$S_5=85$." },
  ],
  as2: [
    { t: "What the question wants", b: "$S_{20}$, the total of the first 20 terms, not the 20th term itself." },
    { t: "The idea", b: "Read $d$ from the list, then use $S_n=\\dfrac{n}{2}\\bigl(2u_1+(n-1)d\\bigr)$." },
    { t: "Working", b: "$d=4$. $S_{20}=\\dfrac{20}{2}\\bigl(22+19\\times 4\\bigr)=10(22+76)=980$." },
    { t: "Answer", b: "$S_{20}=980$." },
  ],
  as3: [
    { t: "What the question wants", b: "The sum $17+27+\\cdots+417$." },
    { t: "The idea", b: "Find $n$ first by setting the last term equal to $417$. Then use $S_n=\\dfrac{n}{2}(u_1+u_n)$." },
    { t: "Working", b: "$d=10$. $17+10(n-1)=417 \\Rightarrow n=41$. Then $S_{41}=\\dfrac{41}{2}(17+417)=41\\times 217=8897$." },
    { t: "Answer", b: "$8897$." },
  ],
  as4: [
    { t: "What the question wants", b: "$d$, given $u_1=-7$ and $S_{20}=620$." },
    { t: "The idea", b: "Put the knowns into the form of $S_n$ that still contains $d$, then solve. Watch the sign of $u_1$." },
    { t: "Working", b: "$620=10\\bigl(-14+19d\\bigr) \\Rightarrow 62=-14+19d \\Rightarrow 76=19d \\Rightarrow d=4$." },
    { t: "Answer", b: "$d=4$." },
  ],
  as5: [
    { t: "What the question wants", b: "$d$, given $u_2=7$ and $S_4=12$." },
    { t: "The idea", b: "Two facts, two unknowns $u_1$ and $d$. Write both as equations, then substitute. $d$ may be negative." },
    { t: "Working", b: "$u_1+d=7$. And $\\dfrac{4}{2}(2u_1+3d)=12 \\Rightarrow 2u_1+3d=6$. Then $2(7-d)+3d=6 \\Rightarrow 14+d=6 \\Rightarrow d=-8$. The terms $15,\\ 7,\\ -1,\\ -9$ add to $12$." },
    { t: "Answer", b: "$d=-8$." },
  ],
  as6: [
    { t: "What the question wants", b: "The number of terms $n$ so that $S_n=1365$." },
    { t: "The idea", b: "$n$ appears in front of a bracket that also has $n$, so we get a quadratic. Keep the positive integer root." },
    { t: "Working", b: "$S_n=\\dfrac{n}{2}(3n+1)=1365 \\Rightarrow 3n^2+n-2730=0$. Discriminant $32761=181^2$, so $n=\\dfrac{-1+181}{6}=30$." },
    { t: "Answer", b: "$n=30$." },
  ],
  as7: [
    { t: "What the question wants", b: "$u_1$ and $u_2$ from a formula for $S_n$." },
    { t: "The idea", b: "$u_1=S_1$ (a total of one term). Then $u_2=S_2-S_1$ (the extra second term)." },
    { t: "Working", b: "$S_1=3-2=1$, so $u_1=1$. $S_2=12-4=8$, so $u_2=8-1=7$." },
    { t: "Answer", b: "$u_1=1$, $u_2=7$." },
  ],
  as8: [
    { t: "What the question wants", b: "An expression for $u_n$ in the form $an+b$, when $n\\ge 2$." },
    { t: "The idea", b: "The question did not say arithmetic, so we use $u_n=S_n-S_{n-1}$, which always works." },
    { t: "Working", b: "$S_{n-1}=(n-1)^2+4(n-1)=n^2+2n-3$. Then $u_n=(n^2+4n)-(n^2+2n-3)=2n+3$. So $a=2$, $b=3$." },
    { t: "Answer", b: "$a=2$, $b=3$ (that is $u_n=2n+3$)." },
  ],
  as9: [
    { t: "What the question wants", b: "$\\displaystyle\\sum_{n=1}^{20}3n=3+6+\\cdots+60$." },
    { t: "The idea", b: "Factor out $3$, or treat it as an arithmetic series of 20 terms." },
    { t: "Working", b: "$3\\times\\dfrac{20\\times 21}{2}=3\\times 210=630$. Same: $\\dfrac{20}{2}(3+60)=630$." },
    { t: "Answer", b: "$630$." },
  ],
  as10: [
    { t: "What the question wants", b: "A sum that starts in the middle: $n=21$ to $n=100$." },
    { t: "The idea", b: "There is no new formula. Take “all the way to 100” minus “the first 20”." },
    { t: "Working", b: "$3\\left(\\dfrac{100\\times 101}{2}-\\dfrac{20\\times 21}{2}\\right)=3(5050-210)=14520$." },
    { t: "Answer", b: "$14520$." },
  ],
  as11: [
    { t: "What the question wants", b: "The total distance over 52 weeks. The word “altogether” means $S_{52}$, not the last week." },
    { t: "Working", b: "$u_{52}=200+51\\times 30=1730$. Then $S_{52}=\\dfrac{52}{2}(200+1730)=26\\times 1930=50180$." },
    { t: "Answer", b: "$50180\\,\\text{m}$." },
  ],
  as12: [
    { t: "What the question wants", b: "How many pieces, $n$." },
    { t: "The idea", b: "We have first, last, and the total length. That is exactly $S_n=\\dfrac{n}{2}(u_1+u_n)$. We do not need $d$ first." },
    { t: "Working", b: "$81=\\dfrac{n}{2}(1.5+7.5)=4.5n \\Rightarrow n=18$." },
    { t: "Answer", b: "$n=18$." },
  ],
  as13: [
    { t: "What the question wants", b: "The sum of multiples of 8 from 1 to 900 inclusive." },
    { t: "The idea", b: "$900$ is not a multiple of 8. The last term is the largest multiple of 8 that is still $\\le 900$." },
    { t: "Working", b: "$8\\times 112=896$ and $8\\times 113=904>900$, so $n=112$ terms from $8$ to $896$. $S=\\dfrac{112}{2}(8+896)=56\\times 904=50624$." },
    { t: "Answer", b: "$50624$." },
  ],
  as14: [
    { t: "What the question wants", b: "$B-A$, where $A$ is the sum of the first 10 terms of $2r+1$ and $B$ is the sum of the first 20." },
    { t: "The idea", b: "The sum from 1 to 20 is the sum from 1 to 10 plus the sum from 11 to 20. So $B=A+C$ and $B-A=C=\\displaystyle\\sum_{r=11}^{20}(2r+1)$. This is the unit 01 split, now with enough terms to use $S_n$." },
    { t: "Working", b: "Those terms are $23,\\ 25,\\ \\ldots,\\ 41$: an arithmetic sequence of $10$ terms, first $23$, last $41$. $$S=\\dfrac{10}{2}(23+41)=5\\times 64=320$$ Check: $A=\\dfrac{10}{2}(3+21)=120$, $B=\\dfrac{20}{2}(3+41)=440$, so $B-A=320$." },
    { t: "Answer", b: "$320$." },
  ],
  g1: [
    { t: "What the question wants", b: "Two things from the list: the first term $u_1$ and the common ratio $r$." },
    { t: "The idea", b: "Geometric means we <em>multiply</em> by the same number each time. That number is $r=\\dfrac{u_2}{u_1}$. Subtracting would be looking for an arithmetic $d$." },
    { t: "Working", b: "$u_1=10$ (the first listed number). $r=\\dfrac{20}{10}=2$. Check: $\\dfrac{40}{20}=2$ as well." },
    { t: "Answer", b: "$u_1=10$, $r=2$." },
  ],
  g2: [
    { t: "What the question wants", b: "The missing third term $a$." },
    { t: "The idea", b: "Each term is the previous one times $r=\\dfrac{1}{2}$. So $a$ is one step on from $8$. We do not need a new formula." },
    { t: "Working", b: "$a=8\\times\\dfrac{1}{2}=4$. Check: the next given term should be $4\\times\\dfrac{1}{2}=2$, which matches." },
    { t: "Answer", b: "$a=4$." },
  ],
  g3: [
    { t: "What the question wants", b: "The common ratio $r$, using all four terms." },
    { t: "The idea", b: "For a geometric sequence, consecutive ratios are equal. Checking every pair is what “use all four terms” means." },
    { t: "Working", b: "$\\dfrac{54}{18}=3$, $\\dfrac{162}{54}=3$, $\\dfrac{486}{162}=3$. So $r=3$." },
    { t: "Answer", b: "$r=3$." },
  ],
  g4: [
    { t: "What the question wants", b: "$r$, given $u_1=5$ and $u_4=40$." },
    { t: "The idea", b: "The booklet says $u_n=u_1 r^{n-1}$. From term 1 to term 4 you multiply by $r$ three times, so the power is $3$, not $4$." },
    { t: "Working", b: "$5r^3=40 \\Rightarrow r^3=8 \\Rightarrow r=2$ (the real cube root)." },
    { t: "Answer", b: "$r=2$." },
  ],
  g5: [
    { t: "What the question wants", b: "$r$ from two non-consecutive terms." },
    { t: "The idea", b: "The ratio of two terms is a power of $r$. The power is the difference of the positions: $u_5/u_2=r^{5-2}=r^3$." },
    { t: "Working", b: "$\\dfrac{324}{12}=27=r^3 \\Rightarrow r=3$." },
    { t: "Answer", b: "$r=3$." },
  ],
  g6: [
    { t: "What the question wants", b: "$u_1$, given two consecutive later terms." },
    { t: "The idea", b: "Consecutive terms make $r$ immediate. Then walk back to $u_1$ with $u_7=u_1 r^{6}$." },
    { t: "Working", b: "$r=\\dfrac{36}{108}=\\dfrac{1}{3}$. Then $108=u_1\\left(\\dfrac{1}{3}\\right)^{6}=\\dfrac{u_1}{729}$, so $u_1=108\\times 729=78732$." },
    { t: "Answer", b: "$u_1=78732$." },
  ],
  g7: [
    { t: "What the question wants", b: "The position $n$ for a given term." },
    { t: "The idea", b: "Divide both sides by $18$ to isolate the power of $3$, then recognise that power." },
    { t: "Working", b: "$3^{n-1}=\\dfrac{1062882}{18}=59049$. Since $3^{10}=59049$, we have $n-1=10$, so $n=11$." },
    { t: "Answer", b: "$n=11$." },
  ],
  g8: [
    { t: "What the question wants", b: "The smallest $n$ with $u_n>1000$." },
    { t: "The idea", b: "This is an inequality for a term, not a sum. Solve $5\\times 2^{n-1}>1000$, then check the integers around the cut." },
    { t: "Working", b: "$2^{n-1}>200$. Now $2^7=128<200$ and $2^8=256>200$, so $n-1=8$ is the first that works: $n=9$. Check: $u_8=640$ and $u_9=1280$." },
    { t: "Answer", b: "$n=9$." },
  ],
  g9: [
    { t: "What the question wants", b: "The first term greater than $500$, rounded to the nearest integer." },
    { t: "The idea", b: "Take logs to find $n$, then compute that term. Always check the neighbouring terms because logs can sit between two integers." },
    { t: "Working", b: "$2(1.05)^{n-1}>500 \\Rightarrow (1.05)^{n-1}>250 \\Rightarrow n-1>\\dfrac{\\ln 250}{\\ln 1.05}\\approx 113.17$. Then $u_{114}=2(1.05)^{113}\\approx 496<500$, so the first success is $n=115$. $u_{115}=2(1.05)^{114}\\approx 520.7$, which rounds to $521$." },
    { t: "Answer", b: "$521$." },
  ],
  g10: [
    { t: "What the question wants", b: "The other possible $r$ (the question already used the positive one)." },
    { t: "The idea", b: "$u_3=u_1 r^{2}$ involves $r$ squared, so the sign is lost. Both $\\pm$ roots make $u_3=8$." },
    { t: "Working", b: "$r^{2}=\\dfrac{8}{18}=\\dfrac{4}{9} \\Rightarrow r=\\pm\\dfrac{2}{3}$. The positive root was given, so the other is $r=-\\dfrac{2}{3}$." },
    { t: "Answer", b: "$r=-\\dfrac{2}{3}$." },
  ],
  g11: [
    { t: "What the question wants", b: "Both possible middle terms $x$." },
    { t: "The idea", b: "Three consecutive geometric terms satisfy $(\\text{middle})^{2}=(\\text{first})(\\text{third})$. A square has two roots." },
    { t: "Working", b: "$x^{2}=5\\times 45=225 \\Rightarrow x=\\pm 15$. Both give a real common ratio ($3$ or $-3$)." },
    { t: "Answer", b: "$15$ and $-15$." },
  ],
  g12: [
    { t: "What the question wants", b: "The common ratio of the three fees." },
    { t: "The idea", b: "Divide a year by the previous year. Check the next pair so it really is geometric." },
    { t: "Working", b: "$r=\\dfrac{2500}{2000}=1.25$. Check: $\\dfrac{3125}{2500}=1.25$ as well." },
    { t: "Answer", b: "$r=1.25$." },
  ],
  g13: [
    { t: "What the question wants", b: "The missing middle year of a geometric population." },
    { t: "The idea", b: "Two years pass from 1996 to 1998, so $40000\\, r^{2}=44100$. The 1997 figure is one step of $r$." },
    { t: "Working", b: "$r=\\sqrt{\\dfrac{44100}{40000}}=\\dfrac{21}{20}=1.05$. Then $40000\\times 1.05=42000$. (Same as the geometric mean $\\sqrt{40000\\times 44100}$.)" },
    { t: "Answer", b: "$42000$." },
  ],
  gs1: [
    { t: "What the question wants", b: "$S_{10}$, the total of the first ten terms — not the tenth term itself." },
    { t: "The idea", b: "We already have $u_1$, $r$ and $n$, so the booklet sum $S_n=\\dfrac{u_1(r^n-1)}{r-1}$ can be used at once." },
    { t: "Working", b: "$S_{10}=\\dfrac{10(2^{10}-1)}{2-1}=10(1024-1)=10230$. (By contrast $u_{10}=10\\times 2^{9}=5120$.)" },
    { t: "Answer", b: "$10230$." },
  ],
  gs2: [
    { t: "What the question wants", b: "$S_{12}$ for $r=\\dfrac{1}{2}$." },
    { t: "The idea", b: "When $|r|<1$, the form $S_n=\\dfrac{u_1(1-r^n)}{1-r}$ keeps the numbers positive and small. The two booklet forms are the same algebra." },
    { t: "Working", b: "$S_{12}=8\\dfrac{1-\\left(\\dfrac{1}{2}\\right)^{12}}{1-\\dfrac{1}{2}}=16\\left(1-\\dfrac{1}{4096}\\right)=\\dfrac{65520}{4096}=15.984375$." },
    { t: "Answer", b: "$15.984375$ (or $\\dfrac{65520}{4096}$)." },
  ],
  gs3: [
    { t: "What the question wants", b: "The six-year total, to the nearest dollar." },
    { t: "The idea", b: "Find $r$ from the first two fees, then use the finite geometric sum with $n=6$. Rounding happens at the end." },
    { t: "Working", b: "$r=1.25$. $S_6=\\dfrac{2000(1.25^{6}-1)}{0.25}=8000(1.25^{6}-1)$. Now $1.25^{6}=3.814697265625$, so $S_6=22517.578\\ldots$, which rounds to $22518$." },
    { t: "Answer", b: "$22518$ dollars." },
  ],
  gs4: [
    { t: "What the question wants", b: "The infinite sum $S_{\\infty}$." },
    { t: "The idea", b: "First find $r$ and check $|r|<1$. Only then is $S_{\\infty}=\\dfrac{u_1}{1-r}$ allowed." },
    { t: "Working", b: "$r=\\dfrac{16}{32}=\\dfrac{1}{2}$, and $\\left|\\dfrac{1}{2}\\right|<1$, so $S_{\\infty}=\\dfrac{32}{1-\\dfrac{1}{2}}=64$." },
    { t: "Answer", b: "$64$." },
  ],
  gs5: [
    { t: "What the question wants", b: "$S_{\\infty}$ of an alternating geometric sequence." },
    { t: "The idea", b: "$r$ is negative here. Convergence still only needs $|r|<1$." },
    { t: "Working", b: "$r=-\\dfrac{9}{27}=-\\dfrac{1}{3}$, and $\\dfrac{1}{3}<1$. Then $S_{\\infty}=\\dfrac{27}{1-\\left(-\\dfrac{1}{3}\\right)}=\\dfrac{27}{\\dfrac{4}{3}}=\\dfrac{81}{4}$." },
    { t: "Answer", b: "$\\dfrac{81}{4}=20.25$." },
  ],
  gs6: [
    { t: "What the question wants", b: "A reason that $S_{\\infty}$ does not exist." },
    { t: "The idea", b: "The only test that matters is $|r|<1$. Here $r=2$, so the terms grow and do not tend to zero." },
    { t: "Working", b: "Positive terms can still have an infinite sum (for example $1+\\dfrac{1}{2}+\\dfrac{1}{4}+\\cdots$). Missing $n$ is irrelevant because infinity is the whole point. The correct reason is $|r|=2>1$." },
    { t: "Answer", b: "$|r|=2>1$, so the terms do not tend to zero." },
  ],
  gs7: [
    { t: "What the question wants", b: "$S_{\\infty}$ using the positive common ratio." },
    { t: "The idea", b: "Find $r$ from $u_3=u_1 r^{2}$ first. Keep the positive root, check $|r|<1$, then sum." },
    { t: "Working", b: "$r^{2}=\\dfrac{8}{18}=\\dfrac{4}{9} \\Rightarrow r=\\dfrac{2}{3}$. Then $S_{\\infty}=\\dfrac{18}{1-\\dfrac{2}{3}}=\\dfrac{18}{\\dfrac{1}{3}}=54$." },
    { t: "Answer", b: "$54$." },
  ],
  gs8: [
    { t: "What the question wants", b: "The smallest $n$ with $S_n>40$." },
    { t: "The idea", b: "Write $S_n$ with the booklet formula, turn the inequality into a power of $3$, then check $S_{n-1}$ and $S_n$ so rounding does not trick us." },
    { t: "Working", b: "$S_n=\\dfrac{1}{81}\\cdot\\dfrac{3^n-1}{2}=\\dfrac{3^n-1}{162}$. Then $3^n-1>6480 \\Rightarrow 3^n>6481$. Now $3^7=2187$ and $3^8=6561$, so $n=8$. Check: $S_7\\approx 13.49<40$ and $S_8\\approx 40.49>40$." },
    { t: "Answer", b: "$n=8$." },
  ],
  gs9: [
    { t: "What the question wants", b: "The first $n$ that pushes $S_n$ past $2047.968$." },
    { t: "The idea", b: "$S_{\\infty}=2048$, so we are a tiny step below infinity. Rewrite $S_n=2048\\bigl(1-2^{-n}\\bigr)$." },
    { t: "Working", b: "$2048\\bigl(1-2^{-n}\\bigr)>2047.968 \\Rightarrow 2^{-n}<2^{-16} \\Rightarrow n\\ge 16$. Check: $S_{15}=2047.9375<2047.968$ and $S_{16}=2047.96875>2047.968$." },
    { t: "Answer", b: "$n=16$." },
  ],
  gs10: [
    { t: "What the question wants", b: "$S_{\\infty}$ as a fraction in lowest terms." },
    { t: "The idea", b: "Read $u_1$ and $r$ from the sigma notation. The $k=0$ term is the first term." },
    { t: "Working", b: "$u_1=\\dfrac{47}{1000}$, $r=\\dfrac{1}{100}$. Then $S_{\\infty}=\\dfrac{47/1000}{1-1/100}=\\dfrac{47/1000}{99/100}=\\dfrac{47}{990}$." },
    { t: "Answer", b: "$\\dfrac{47}{990}$." },
  ],
  gs11: [
    { t: "What the question wants", b: "The upper end of the open interval of $x$ for which the series converges." },
    { t: "The idea", b: "A geometric series converges only when $|r|<1$. Here $r=4x-3$." },
    { t: "Working", b: "$-1<4x-3<1 \\Rightarrow 2<4x<4 \\Rightarrow \\dfrac{1}{2}<x<1$. The largest possible $x$ in this open interval is bounded by $1$ (and $x=1$ itself is not allowed)." },
    { t: "Answer", b: "The upper bound is $1$." },
  ],
  gs12: [
    { t: "What the question wants", b: "$S_{\\infty}$ at $x=0.7$, as a reduced fraction." },
    { t: "The idea", b: "Compute $r$, check $|r|<1$, then $S_{\\infty}=\\dfrac{u_1}{1-r}$." },
    { t: "Working", b: "$r=4(0.7)-3=-0.2$. Then $S_{\\infty}=\\dfrac{2}{1-(-0.2)}=\\dfrac{2}{1.2}=\\dfrac{5}{3}$." },
    { t: "Answer", b: "$\\dfrac{5}{3}$." },
  ],
  r1: [
    { t: "What the question wants", b: "$S_3$, the sum of the first three terms of a recursive sequence." },
    { t: "The idea", b: "A recursive rule only gives the next term from the one you have. Write $u_1,u_2,u_3$ in order, then add. Do not jump to a sum formula until the terms are known." },
    { t: "Working", b: "$u_1=10$, $u_2=20$, $u_3=30$. Then $S_3=10+20+30=60$." },
    { t: "Answer", b: "$60$." },
  ],
  r2: [
    { t: "What the question wants", b: "The common ratio $r$ in the recursive rule $u_{n+1}=r\\,u_n$." },
    { t: "The idea", b: "Multiplying by the same $r$ each time is a geometric sequence. From unit 04, $u_3=u_1 r^{2}$. The square gives two roots; positivity keeps the positive one." },
    { t: "Working", b: "$7r^{2}=28 \\Rightarrow r^{2}=4 \\Rightarrow r=\\pm 2$. Positive terms mean $r=2$, not $r=-2$." },
    { t: "Answer", b: "$r=2$." },
  ],
  r3: [
    { t: "What the question wants", b: "$u_3$ from a mixed recursive rule." },
    { t: "The idea", b: "This is not purely arithmetic and not purely geometric. You cannot skip $u_2$." },
    { t: "Working", b: "$u_2=2(1)+10=12$. Then $u_3=2(12)+10=34$." },
    { t: "Answer", b: "$u_3=34$." },
  ],
  r4: [
    { t: "What the question wants", b: "$u_3$ from a mixed recursive rule." },
    { t: "The idea", b: "The rule $u_{n+1}=3u_n-2$ is neither “add a constant” nor “multiply by a constant”. You cannot skip $u_2$." },
    { t: "Working", b: "$u_2=3(4)-2=10$. Then $u_3=3(10)-2=28$." },
    { t: "Answer", b: "$u_3=28$." },
  ],
  r5: [
    { t: "What the question wants", b: "The total number of cans, which is $1+2+\\cdots+20$." },
    { t: "The idea", b: "The row sizes are arithmetic. The total is the triangular number $S_{20}=\\dfrac{n(n+1)}{2}$." },
    { t: "Working", b: "$S_{20}=\\dfrac{20}{2}(1+20)=10\\times 21=210$." },
    { t: "Answer", b: "$210$ cans." },
  ],
  r6: [
    { t: "What the question wants", b: "The bottom-row size $n$ given the triangular total $3240$." },
    { t: "The idea", b: "Solve $\\dfrac{n(n+1)}{2}=3240$. Keep the positive integer root (a row count cannot be negative)." },
    { t: "Working", b: "$n^{2}+n-6480=0$. Discriminant $1+25920=25921=161^{2}$, so $n=\\dfrac{-1+161}{2}=80$." },
    { t: "Answer", b: "$80$ cans." },
  ],
  r7: [
    { t: "What the question wants", b: "How many integers sit in the 20th group — the size of the group, not the last integer in it." },
    { t: "The idea", b: "The group sizes themselves form an arithmetic sequence $1,4,7,10,\\ldots$ with $d=3$. Find $u_{20}$ of that sequence." },
    { t: "Working", b: "$u_n=1+3(n-1)=3n-2$. Then $u_{20}=3(20)-2=58$." },
    { t: "Answer", b: "$58$ integers." },
  ],
  m1: [
    { t: "What the question wants", b: "The value of $k$ that makes the three terms arithmetic." },
    { t: "The idea", b: "Equal gaps mean twice the middle equals the two sides. Write that down before any algebra." },
    { t: "Working", b: "$2(2k)=k+(k+60) \\Rightarrow 4k=2k+60 \\Rightarrow k=30$. The terms are $30,\\ 60,\\ 90$ with $d=30$." },
    { t: "Answer", b: "$k=30$." },
  ],
  m2: [
    { t: "What the question wants", b: "The value of $k$ that makes the same three terms geometric." },
    { t: "The idea", b: "Now the test is $(\\text{middle})^{2}=(\\text{first})(\\text{third})$. Do not reuse the arithmetic test — that finds a different $k$." },
    { t: "Working", b: "$(2k)^{2}=k(k+60) \\Rightarrow 4k^{2}=k^{2}+60k$. Since $k\\neq 0$, divide by $k$: $3k=60$, so $k=20$. Terms $20,\\ 40,\\ 80$ with $r=2$." },
    { t: "Answer", b: "$k=20$." },
  ],
  m3: [
    { t: "What the question wants", b: "$k$ so that $k-5$, $3-2k$, $5k+3$ are arithmetic." },
    { t: "The idea", b: "The arithmetic condition is linear, so there is one value of $k$. (The geometric case for the same three terms is a different, usually quadratic, equation.)" },
    { t: "Working", b: "$2(3-2k)=(k-5)+(5k+3) \\Rightarrow 6-4k=6k-2 \\Rightarrow 8=10k \\Rightarrow k=\\dfrac{4}{5}$." },
    { t: "Answer", b: "$k=\\dfrac{4}{5}$." },
  ],
  m4: [
    { t: "What the question wants", b: "The common ratio of the geometric sequence made from $u_3,u_4,u_7$." },
    { t: "The idea", b: "The show-that result $a=-\\dfrac{3}{2}d$ lets us write those three terms in $d$ only. Then $r$ is a ratio of two of them." },
    { t: "Working", b: "$u_3=a+2d=\\dfrac{1}{2}d$, $u_4=\\dfrac{3}{2}d$, $u_7=\\dfrac{9}{2}d$. So $r=\\dfrac{u_4}{u_3}=3$. Check: $\\dfrac{u_7}{u_4}=3$ as well." },
    { t: "Answer", b: "$r=3$." },
  ],
  m5: [
    { t: "What the question wants", b: "The common ratio of the geometric sequence." },
    { t: "The idea", b: "The three geometric terms sit at arithmetic positions $1$, $11$ and $16$. The second jump is half the first ($5$ steps after $10$ steps), which forces $r=\\dfrac{1}{2}$." },
    { t: "Working", b: "Let the arithmetic terms be $a$, $a+10d$, $a+15d$. Then $(a+10d)^{2}=a(a+15d)$ gives $a=-20d$ (using $d\\neq 0$ and the terms different). So $r=\\dfrac{a+10d}{a}=\\dfrac{1}{2}$." },
    { t: "Answer", b: "$r=\\dfrac{1}{2}$." },
  ],
  m6: [
    { t: "What the question wants", b: "The greatest partial sum $S_n$ of a decreasing arithmetic sequence." },
    { t: "The idea", b: "Sums increase while terms are still positive, then start falling once terms become negative. Find the last positive term, then compare the nearby sums." },
    { t: "Working", b: "$80-6.32(n-1)=0 \\Rightarrow n-1\\approx 12.66$. So $u_{13}>0$ and $u_{14}<0$. Then $S_{13}=\\dfrac{13}{2}\\bigl(160+12(-6.32)\\bigr)=\\dfrac{13}{2}\\times 84.16=547.04$. Adding $u_{14}<0$ makes $S_{14}$ smaller." },
    { t: "Answer", b: "$547.04$." },
  ],
  m7: [
    { t: "What the question wants", b: "The time for the 10th length — a single term, not a total." },
    { t: "The idea", b: "Arithmetic: $u_n=u_1+(n-1)d$." },
    { t: "Working", b: "$u_{10}=2+9\\times 0.1=2.9$." },
    { t: "Answer", b: "$2.9$ minutes." },
  ],
  m8: [
    { t: "What the question wants", b: "The total time for 10 lengths, so $S_{10}$ of a geometric sequence." },
    { t: "The idea", b: "Use the finite geometric sum. Round only at the end, to 3 decimal places." },
    { t: "Working", b: "$S_{10}=\\dfrac{2(1.05^{10}-1)}{0.05}=40(1.05^{10}-1)$. Now $1.05^{10}\\approx 1.628894627$, so $S_{10}\\approx 25.155785$, which is $25.156$ to 3 d.p." },
    { t: "Answer", b: "$25.156$ minutes." },
  ],
  x1a: [
    { t: "What the question wants", b: "The 13th term $u_{13}$." },
    { t: "The idea", b: "You only know two terms, so $d$ is missing. Between term 1 and term 5 there are $4$ steps, not $5$." },
    { t: "Working", b: "$d=\\dfrac{10-30}{4}=-5$. Then $u_{13}=30+12(-5)=30-60=-30$. Negative is fine: the sequence is decreasing." },
    { t: "Answer", b: "$u_{13}=-30$." },
  ],
  x1b: [
    { t: "What the question wants", b: "The number of terms $n$ making the sum zero. This is $S_n=0$, not a term equal to zero." },
    { t: "The idea", b: "$S_n=\\dfrac{n}{2}\\bigl(2u_1+(n-1)d\\bigr)=0$. The factor $n$ is not zero, so the bracket is zero." },
    { t: "Working", b: "$60+(n-1)(-5)=0 \\Rightarrow 65=5n \\Rightarrow n=13$. The list walks from $30$ down through $0$ and the totals cancel." },
    { t: "Answer", b: "$n=13$." },
  ],
  x2: [
    { t: "What the question wants", b: "The position $k$ of the zero term." },
    { t: "The idea", b: "You were not given $u_1$ or $d$. Translate both facts into equations in $u_1$ and $d$ first. Only then set $u_k=0$." },
    { t: "Working", b: "$u_1+9d=20$ and $\\dfrac{25}{2}(2u_1+24d)=125 \\Rightarrow u_1+12d=5$. Subtract: $3d=-15 \\Rightarrow d=-5$, then $u_1=65$. Then $65+(k-1)(-5)=0 \\Rightarrow k=14$." },
    { t: "Answer", b: "$k=14$." },
  ],
  x3a: [
    { t: "What the question wants", b: "$k$ in the arithmetic case." },
    { t: "The idea", b: "This part says arithmetic, so use $2u_2=u_1+u_3$. Save the geometric condition for a later part." },
    { t: "Working", b: "$2(3-2k)=(k-5)+(5k+3) \\Rightarrow 6-4k=6k-2 \\Rightarrow k=\\dfrac{4}{5}$. Then $u_3=5\\left(\\dfrac{4}{5}\\right)+3=7$." },
    { t: "Answer", b: "$k=\\dfrac{4}{5}$." },
  ],
  x3b: [
    { t: "What the question wants", b: "The common ratio when $k=12$. (The infinite sum does not exist.)" },
    { t: "The idea", b: "Substitute $k=12$ to get three numbers, then $r=u_2/u_1$. Check it matches $u_3/u_2$." },
    { t: "Working", b: "$u_1=7$, $u_2=-21$, $u_3=63$. Then $r=\\dfrac{-21}{7}=-3$. And $|r|=3>1$, so the terms grow and $S_{\\infty}$ does not exist." },
    { t: "Answer", b: "$r=-3$." },
  ],
  x3c: [
    { t: "What the question wants", b: "The other value of $k$ that makes the sequence geometric." },
    { t: "The idea", b: "Geometric means $u_2^{2}=u_1 u_3$. Expanding gives a quadratic. One root is the $k=12$ already used." },
    { t: "Working", b: "$(3-2k)^{2}=(k-5)(5k+3)$ simplifies to $k^{2}-10k-24=0=(k-12)(k+2)$. Discard $k=12$. The other value is $k=-2$, with terms $-7,\\ 7,\\ -7$ and $r=-1$." },
    { t: "Answer", b: "$k=-2$." },
  ],
  x4a: [
    { t: "What the question wants", b: "The second term of the geometric sequence." },
    { t: "The idea", b: "Find $r$ from $u_4=u_1 r^{3}$, then $u_2=u_1 r$." },
    { t: "Working", b: "$50 r^{3}=3.2 \\Rightarrow r^{3}=0.064 \\Rightarrow r=0.4$. Then $u_2=50\\times 0.4=20$." },
    { t: "Answer", b: "$20$." },
  ],
  x4b: [
    { t: "What the question wants", b: "The greatest $S_n$ of the arithmetic sequence that starts $50,\\ 20,\\ \\ldots$ at positions $1$ and $11$." },
    { t: "The idea", b: "Find $d$ first. Then find the last positive term and compare nearby sums." },
    { t: "Working", b: "$50+10d=20 \\Rightarrow d=-3$. Then $50-3(n-1)=0 \\Rightarrow n-1\\approx 16.67$, so $u_{17}>0$ and $u_{18}<0$. $S_{17}=\\dfrac{17}{2}\\bigl(100+16(-3)\\bigr)=442$. Adding $u_{18}<0$ makes $S_{18}$ smaller." },
    { t: "Answer", b: "$442$." },
  ],
  x5a: [
    { t: "What the question wants", b: "The infinite sum as a reduced fraction." },
    { t: "The idea", b: "The $k=0$ term is $u_1$. Each next term multiplies by $\\dfrac{1}{100}$." },
    { t: "Working", b: "$S_{\\infty}=\\dfrac{47/1000}{1-1/100}=\\dfrac{47}{990}$." },
    { t: "Answer", b: "$\\dfrac{47}{990}$." },
  ],
  x5b: [
    { t: "What the question wants", b: "The repeating decimal $0.2474747\\ldots$ as a reduced fraction." },
    { t: "The idea", b: "Split off the non-repeating $0.2$, then reuse the series from the previous part for $0.0474747\\ldots$." },
    { t: "Working", b: "$0.2474747\\ldots=0.2+0.0474747\\ldots=\\dfrac{1}{5}+\\dfrac{47}{990}=\\dfrac{198}{990}+\\dfrac{47}{990}=\\dfrac{245}{990}=\\dfrac{49}{198}$." },
    { t: "Answer", b: "$\\dfrac{49}{198}$." },
  ],
};

export function getWorked(problem) {
  if (problem?.worked?.length) return problem.worked;
  if (problem?.id && worked[problem.id]) return worked[problem.id];
  const fromHints = (problem?.hints || []).map((h) => ({ t: h.k, b: h.b }));
  return [...fromHints, { t: "Answer", b: problem?.solution || "" }];
}
